name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: build-release
    strategy:
      fail-fast: false
      matrix:
        build: [linux, macos, win-msvc]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-2025
          rust: stable
          target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev pkg-config libgtk-3-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtg-proxy-creator-rust-${{ matrix.os }}
          path: |
            target/${{ matrix.target }}/release/mtg-proxy-creator-rust
            target/${{ matrix.target }}/release/mtg-proxy-creator-rust.exe
